FROM ubuntu:latest

RUN \
     apt-get update -y && \
     apt-get install -y --no-install-recommends apt-utils && \
     apt-get install curl ca-certificates libvshadow-utils util-linux iproute2 iputils-ping software-properties-common -y && \
     apt-get autoclean

RUN apt-get install gcc git bzr jq pkg-config curl clang build-essential hwloc wget libhwloc-dev ocl-icd-opencl-dev -y

LABEL maintainer="MinIO Inc <dev@min.io>"

COPY minio /usr/bin/
COPY dockerscripts/docker-entrypoint.sh /usr/bin/

RUN chmod +x /usr/bin/minio && \
    chmod +x /usr/bin/docker-entrypoint.sh

EXPOSE 9000

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]

VOLUME ["/data"]

CMD ["minio"]